### ISSUE TITLE
Wrong rights on lib/puppet/provider/gms_webhook/github.rb

### ISSUE THREAD

**Issue by mvisonneau** [abrader/abrader-gms#28]
Hey,

Got this error after upgrading to 1.0.2 :
```
Error: /File[/opt/puppetlabs/puppet/cache/lib]: Failed to generate additional resources using 'eval_generate': Error 400 on SERVER: Permission denied - /etc/puppetlabs/code/environments/production/modules/gms/lib/puppet/provider/gms_webhook/github.rb
```

Adding missing read right on others solves it :
```
chmod o+r /etc/puppetlabs/code/environments/production/modules/gms/lib/puppet/provider/gms_webhook/github.rb
```

Cheers!

**Comment by abrader** [comment]
@mvisonneau Well, that is lame.  My apologies.  Will cut another release soon.  Thanks for the heads up.  Confirmed the permissions issue when I did a puppet module install abrader/gms as well.

**Comment by mvisonneau** [comment]
No worries, thanks!

**Comment by walterheck** [comment]
@abrader can you push a new release for this? It's currently blocking this module from working properly..

**Comment by abrader** [comment]
@walterheck will do today.

**Comment by natemccurdy** [comment]
Did this ever get fixed? ...in master?

**Comment by djjudas21** [comment]
Still seeing this in `1.0.2` as well. Any chance of a fixed version? Thanks!

**Comment by natemccurdy** [comment]
If you're using Code Manager and seeing this issue even on `1.0.2`, you might be running into a bug where file permissions (mainly the execute bit) don't change on your master when deploying a new version of a module.

The fix for me was to delete the `gms` module from the `code` and `code-staging` directory on my master(s) then redeploy with Code Manager.

That same bug might also affect `r10k` as well, but I haven't verified that.

**Comment by djjudas21** [comment]
I am indeed using `r10k`

**Comment by rjhornsby** [comment]
I'm using r10k.  The bug (a minor oversight, really) seems to be in the module itself as packaged on the Forge, not in Puppet or r10k.  The zipfile of 1.0.2 from github looks like it has the right permissions, which makes me think the problem is in the package the Forge is supplying.

@mvisonneau's work-around, even if temporary, is the right one: setting the read bit.  No exec permissions are needed.

**Comment by abrader** [comment]
@mvisonneau @rjhornsby @djjudas21 @natemccurdy @walterheck Please inspect [release 1.0.3](https://forge.puppet.com/v3/files/abrader-gms-1.0.3.tar.gz) for similar permission issues.  I inspected tarball prior to upload to Forge and confirmed all were set correctly.

**Comment by djjudas21** [comment]
@abrader `1.0.3` seems to work for me, thanks!

**Comment by rjhornsby** [comment]
>  Please inspect release 1.0.3 for similar permission issues. I inspected tarball prior to upload to
> Forge and confirmed all were set correctly.

1.0.3 looks like that fixed it. Thanks!

**Comment by mvisonneau** [comment]
@abrader works for me as well ! Closing the issue then, thanks for the fix :)
