### ISSUE TITLE
[Feature] Support for stash in git_webhook

### ISSUE THREAD

**Issue by joshuabaird** [abrader/abrader-gms#9]
Any plans to include support for Stash?

**Comment by abrader** [comment]
As you will note in the [README](https://github.com/abrader/abrader-gms/blob/master/README.md), I mentioned Stash support is in the works.  The OAUTH stuff is taking some time.  I am writing it from scratch.  Why OAUTH from scratch?  The intent of this module is to not require any other dependencies except for Puppet stdlib since it's main purpose is aiding in the standup of Puppet infrastructure.

Next time consider adding the enhancement label and a feature header since this isn't an issue.

**Comment by joshuabaird** [comment]
Excellent, thanks for the info and all of the work on this module.

**Comment by abrader** [comment]
Released.

abrader-gms-1.0.0.tar.gz

Now with Stash support!

:metal:
